#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 7
#define MS_VERSION_MINOR 2
#define MS_VERSION_REV 1
#define MS_VERSION "7.2.1"
#define MS_VERSION_NUM  70201 

#endif

