#sysUpdateのどのレコードで、予測演算開始を判断するのかを設定,
#config_rain.iniの設定内容により、本設定の行数が変動する。（例えば、気象庁なら３つの雨だが、国土交通省なら２つだけ。とか。）,
#,
#いまのところ、次のような種類が存在している。,
#,
#10,テレメータ（テレメータ雨量を含む）
#15,国土交通省レーダ実況
#20,国道交通省レーダ予測（FRICSレーダ予測を含む）
#25,気象庁レーダ実況
#26,気象庁降水ナウキャスト
#27,気象庁降水短時間予想
#30,気象協会51時間予測
#40,手入力雨量
#,
#予測演算開始を判断するデータ種類,備考
#idsysupdate,note
 0,予測結果,               0, 0,d:\data\datetime\jmbsc\DateCalc.txt
10,テレメータ,             0, 0,d:\data\datetime\jmbsc\DateTele.txt
25,気象庁レーダ実況,       0, 0,d:\data\datetime\jmbsc\DateJmaJ.txt
26,気象庁降水ナウキャスト, 0, 0,d:\data\datetime\jmbsc\DateJmaN.txt
27,気象庁降水短時間予想,  30,50,d:\data\datetime\jmbsc\DateJmaY.txt
28,気象庁レーダ実況add,       0, 0,d:\data\datetime\jmbsc\DateJmaJadd.txt
