#ID,OriginalDirectoryName,OriginalFileName,OriginalDataDepth,WriteDirectoryName,WriteRepeatNum,SysUpdateID,FlagKml,JY
0,forecast,Z__C_RJTD_*_SRF_GPV_Ggis1km_Prr60lv_ANAL_grib2.bin,1,JmaJ,1,25,True,J
1,forecast,Z__C_RJTD_*_SRF_GPV_Ggis1km_Prr60lv_FH01-06_grib2.bin,6,JmaY,1,27,True,Y
2,forecast,Z__C_RJTD_*_SRF_GPV_Ggis1km_Prr60lv_Aper10min_ANAL_grib2.bin,1,JmaJ,1,31,True,J
3,forecast,Z__C_RJTD_*_SRF_GPV_Ggis1km_Prr60lv_Fper10min_FH01-06_grib2.bin,6,JmaY,1,32,True,Y
#解説（excelで開いたときにおかしなことにならないよう、カンマを意図的に外しています）
#ID　　　　　　　　　　　 0から始まる整数（0 1 2 ・・という感じで与えて下さい）
#OriginalDirectoryName　　D:\data\mesh\jmbsc\forecast\2011\10\25\Z__C_RJTD_20111025043000_SRF_GPV_Ggis1km_Prr60lv_ANAL_grib2.bin等のforecastやnowcastの部分
#OriginalFileName　　　　 D:\data\mesh\jmbsc\forecast\2011\10\25\Z__C_RJTD_20111025043000_SRF_GPV_Ggis1km_Prr60lv_ANAL_grib2.bin等の最後のファイル名の部分
#OriginalDataDepth　　　　データの予測方向の深さ（実況の場合は1を指定）（ナウキャストの場合は6個あるので6を指定）
#WriteDirectoryName　　　 データを書き込む時のD:\data\mesh\hyougo\JmaJ\2011\10\10251330.dat等のJmaJの部分
#WriteRepeatNum　　　　　 降水短時間等の場合、予測が6しかないですが、それを36個にしたい時6を指定（例えば予測値が1 2 3 4 5 6だった場合、書き込み結果は1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6になる）
#SysUpdateID              config_sysupdate.iniにおけるID
#FlagKml　　　　　　　　　KmlまたはKmzを作成するか否か
#JY                       dat2kml.exeは、inputとoutputのほかにJかYかを指定する必要があるが、ここでそれを設定する
